[package]
name = "bevy_flurx_wry"
version = "0.1.0"
edition = "2021"
authors = ["elm"]
description = "Provides a mechanism to create a webview based on `wry`."
repository = "https://github.com/not-elm/bevy_flurx_wry"
categories = ["gui", "game-development"]
keywords = ["game", "gamedev", "bevy", "wry"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace]
resolver = "2"
members = [
    "crates/*",
    "examples/bug_check",
]
exclude = [
    "tooling",
]

[dependencies]
bevy_flurx_wry_core = { path = "./crates/core", version = "0.1.0" }
bevy_flurx_ipc = { path = "crates/ipc", version = "0.1.0" }
bevy_flurx_wry_api = { path = "crates/api", version = "0.1.0" }

[dev-dependencies]
bevy = "0.13.2"
bevy_flurx = { workspace = true }

[lints]
workspace = true

[workspace.dependencies]
bevy_flurx = { path = "../bevy_flurx", version = "0.5.1" }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"

[workspace.lints.clippy]
type_complexity = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
undocumented_unsafe_blocks = "warn"
redundant_else = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"

[workspace.lints.rust]
missing_docs = "warn"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]