[workspace]
members = [
    "crates/*", "examples/bug_check",
]
exclude = [
    "tooling",
    "crates/api",
    "crates/ultralight_2d"
]

[package]
name = "bevy_flurx_webview"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_flurx_wry = { path = "./crates/wry" }

[dev-dependencies]
bevy-inspector-egui = "0.24.0"

[workspace.dependencies]
bevy_flurx = { path = "../bevy_flurx", version = "0.5.1" }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"


[workspace.lints.clippy]
type_complexity = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
undocumented_unsafe_blocks = "warn"
redundant_else = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"

[workspace.lints.rust]
#missing_docs = "warn"