[package]
name = "bevy_flurx_ipc_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.82"
syn = { version = "2.0.63", features = ["full", "extra-traits"] }
quote = "1.0.36"