[package]
name = "bevy_flurx_wry_api"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false }
bevy_flurx = { workspace = true }
bevy_flurx_ipc = { path = "../ipc", version = "0.1.0" }
bevy_flurx_wry_core = { path = "../core", version = "0.1.0" }
serde = { workspace = true }

[lints]
workspace = true
