[package]
name = "bevy_flurx_wry_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_ui"
] }
wry = { version = "0.39.5" }
bevy_flurx_ipc = { path = "../ipc", version = "0.1.0" }
bevy_flurx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
mouse-rs = "0.4.2"

[dev-dependencies]
bevy = "0.13.2"
bevy_test_helper = { git = "https://github.com/not-elm/bevy_test_helper" }

[lints]
workspace = true