[package]
name = "bug_check"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = "0.13.2"
bevy_flurx_wry = { path = "../../crates/wry" }
serde = { version = "1.0.202", features = ["derive"] }

[lints]
workspace = true
